services:
  nginxproxymanager:
    image: jlesage/nginx-proxy-manager
    container_name: nginxproxymanager
    restart: unless-stopped 
    environment:
      TZ: America/New_York
    ports:
      - '80:8080'
      - '81:8181'
      - '443:4443' 
    volumes:
      - ./appdata/nginx-proxy-manager:/config:rw
  
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    volumes:
      - ./uptime-kuma:/app/data
    ports:
      - 3001:3001
    restart: unless-stopped
  
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    environment:
      TZ: America/New_York
      N8N_SECURE_COOKIE: false
    volumes:
      - ./n8n_data:/home/node/.n8n
    ports:
      - 5678:5678
    restart: unless-stopped