services:
  nginxproxymanager:
    image: jlesage/nginx-proxy-manager
    container_name: nginxproxymanager
    restart: unless-stopped 
    environment:
      TZ: America/New_York
    ports:
      - '80:8080'
      - '81:8181'
      - '443:4443' 
    volumes:
      - ./appdata/nginx-proxy-manager:/config:rw
  
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    volumes:
      - ./uptime-kuma:/app/data
    ports:
      - 3001:3001
    restart: unless-stopped